161007

diff --git a/fc_scripts-mod/cmaq/cmaq_run b/fc_scripts-mod/cmaq/cmaq_run
--- a/fc_scripts-mod/cmaq/cmaq_run
+++ b/fc_scripts-mod/cmaq/cmaq_run
@@ -45,73 +45,73 @@ export MY_OUTPUT=$MYDIR/outputs
 
 $ECHO "CMAQ Initial Time = $INIT_TIME, My directory = $MYDIR"
 
-#####./cleanup
-#####
-#####if [ $CTM_COLD_START -eq 0 -a $CTM_CLEAN_OUTPUT -eq 1 ]; then
-#####  ./find_day0 $INIT_TIME
-#####  stat=$?
-#####  if [ $stat -eq 1 ]; then
-#####    $ECHO "Failed to run ./find_day0 $INIT_TIME"
-#####    exit 1
-#####  elif [ $stat -eq 2 ]; then
-#####    $ECHO "WARNING: Cannot find day0 CMAQ output files $INIT_TIME"
-#####    export CTM_COLD_START=1
-#####    $ECHO "WARNING: Force the CMAQ run to cold start, CTM_COLD_START=${CTM_COLD_START}"
-#####  fi
-#####fi
-#####
-#####Ncpu=`$PATH_SYSDIR/bin/mpi_total_cpus` || {
-#####  $ECHO "Failed to run $PATH_SYSDIR/bin/mpi_total_cpus"
-#####  exit 1
-#####}
-#####
-#####/bin/cp ${MPIHostFile} $MYDIR/runfiles/runfiles/nodes  || {
-#####  $ECHO "Failed to copy ${MPIHostFile} to $MYDIR/runfiles/runfiles/nodes"
-#####  exit 1
-#####  }
-#####
-#####export NPROCS="$Ncpu"
-#####let "NPCOL = NPROCS / 2"
-#####export NPCOL_NPROW="$NPCOL 2"
-#####
-#####$PATH_SYSDIR/bin/start_mpd || {
-#####  $ECHO "Failed to run $PATH_SYSDIR/bin/start_mpd"
-#####  exit 1
-#####}
-#####
-#####if [ $CTM_USE_SMOKE -eq 0 ]; then
-#####  # Pick emission data from pre-generated data
-#####  export PICKEMIS=1
-#####else
-#####  # Copy data from SMOKE output
-#####  export PICKEMIS=0
-#####fi
-#####
-#####$ECHO "PICKEMIS=$PICKEMIS"
-#####if [ $PICKEMIS -eq 0 ]; then
-#####  # Copy emission data from $PATH_DATADIR/smoke/... to inputs/emiss/*
-#####  FromEmissData=$DATA_SMOKE_OUTPUT/${INIT_TIME:0:4}/${INIT_TIME:0:6}/${INIT_TIME}/cmaq
-#####  if [ ! -e $FromEmissData ]; then
-#####    $ECHO "CTM_USE_SMOKE=${CTM_USE_SMOKE}. No input emission data found in $FromEmissData"
-#####    exit 1
-#####  fi
-#####  $ECHO "Copy emission data from $FromEmissData"
-#####  /usr/bin/rsync -av $FromEmissData/ inputs/emiss/ || {
-#####    $ECHO "Failed to run /usr/bin/rsync -av $FromEmissData/ inputs/emiss/"
-#####    exit 1
-#####  }
-#####fi
-#####
-#####export M3HOME=$MYDIR/src
-#####$ECHO "M3HOME set to $M3HOME"
-#####
-#####$ECHO ./Whole_OP.csh $INIT_TIME $MCIP_DIR
-#####./Whole_OP.csh $INIT_TIME $MCIP_DIR
-#####if [ $? -ne 0 ]; then
-#####  $ECHO "Failed to run ./Whole_OP.csh $INIT_TIME $MCIP_DIR"
-#####  exit 1
-#####fi
-#####
+./cleanup
+
+if [ $CTM_COLD_START -eq 0 -a $CTM_CLEAN_OUTPUT -eq 1 ]; then
+  ./find_day0 $INIT_TIME
+  stat=$?
+  if [ $stat -eq 1 ]; then
+    $ECHO "Failed to run ./find_day0 $INIT_TIME"
+    exit 1
+  elif [ $stat -eq 2 ]; then
+    $ECHO "WARNING: Cannot find day0 CMAQ output files $INIT_TIME"
+    export CTM_COLD_START=1
+    $ECHO "WARNING: Force the CMAQ run to cold start, CTM_COLD_START=${CTM_COLD_START}"
+  fi
+fi
+
+Ncpu=`$PATH_SYSDIR/bin/mpi_total_cpus` || {
+  $ECHO "Failed to run $PATH_SYSDIR/bin/mpi_total_cpus"
+  exit 1
+}
+
+/bin/cp ${MPIHostFile} $MYDIR/runfiles/runfiles/nodes  || {
+  $ECHO "Failed to copy ${MPIHostFile} to $MYDIR/runfiles/runfiles/nodes"
+  exit 1
+  }
+
+export NPROCS="$Ncpu"
+let "NPCOL = NPROCS / 2"
+export NPCOL_NPROW="$NPCOL 2"
+
+$PATH_SYSDIR/bin/start_mpd || {
+  $ECHO "Failed to run $PATH_SYSDIR/bin/start_mpd"
+  exit 1
+}
+
+if [ $CTM_USE_SMOKE -eq 0 ]; then
+  # Pick emission data from pre-generated data
+  export PICKEMIS=1
+else
+  # Copy data from SMOKE output
+  export PICKEMIS=0
+fi
+
+$ECHO "PICKEMIS=$PICKEMIS"
+if [ $PICKEMIS -eq 0 ]; then
+  # Copy emission data from $PATH_DATADIR/smoke/... to inputs/emiss/*
+  FromEmissData=$DATA_SMOKE_OUTPUT/${INIT_TIME:0:4}/${INIT_TIME:0:6}/${INIT_TIME}/cmaq
+  if [ ! -e $FromEmissData ]; then
+    $ECHO "CTM_USE_SMOKE=${CTM_USE_SMOKE}. No input emission data found in $FromEmissData"
+    exit 1
+  fi
+  $ECHO "Copy emission data from $FromEmissData"
+  /usr/bin/rsync -av $FromEmissData/ inputs/emiss/ || {
+    $ECHO "Failed to run /usr/bin/rsync -av $FromEmissData/ inputs/emiss/"
+    exit 1
+  }
+fi
+
+export M3HOME=$MYDIR/src
+$ECHO "M3HOME set to $M3HOME"
+
+$ECHO ./Whole_OP.csh $INIT_TIME $MCIP_DIR
+./Whole_OP.csh $INIT_TIME $MCIP_DIR
+if [ $? -ne 0 ]; then
+  $ECHO "Failed to run ./Whole_OP.csh $INIT_TIME $MCIP_DIR"
+  exit 1
+fi
+
 $ECHO ./check_output $INIT_TIME
 ./check_output $INIT_TIME || {
   $ECHO "Failed to run ./check_output $INIT_TIME"
