160809

diff --git a/PATH-SCRIPT-201607/mcip/move_output b/PATH-SCRIPT-201607/mcip/move_output
--- a/PATH-SCRIPT-201607/mcip/move_output
+++ b/PATH-SCRIPT-201607/mcip/move_output
@@ -26,26 +26,26 @@ if [ ! -d $OutputDir ]; then
   }
 fi
 
-#for d in 27 9 3 1
-for d in ${G_DOMAINS_RES_gov}
+#for DOMAINS_RES in 27 9 3 1
+for DOMAINS_RES in ${G_DOMAINS_RES_gov}
 do
-  [ -f outputs/$d/GRIDDESC ] || {
-    echo "outputs/$d/GRIDDESC does not exist"
+  [ -f outputs/$DOMAINS_RES/GRIDDESC ] || {
+    echo "outputs/$DOMAINS_RES/GRIDDESC does not exist"
     exit 1
   }
 done
 
-#for d in 27 9 3 1 
-for d in ${G_DOMAINS_RES_gov}
+#for DOMAINS_RES in 27 9 3 1 
+for DOMAINS_RES in ${G_DOMAINS_RES_gov}
 do
-  if [ ! -d $OutputDir/${d}km ]; then
-    /bin/mkdir $OutputDir/${d}km || {
-      echo "Failed to create output subdirectory $OutputDir/${d}km"
+  if [ ! -d $OutputDir/${DOMAINS_RES}km ]; then
+    /bin/mkdir $OutputDir/${DOMAINS_RES}km || {
+      echo "Failed to create output subdirectory $OutputDir/${DOMAINS_RES}km"
       exit 1
     }
   fi
-  /usr/bin/rsync -av outputs/$d/ $OutputDir/${d}km/ || {
-    echo "Failed to run /usr/bin/rsync -av outputs/$d/ $OutputDir/${d}km/"
+  /usr/bin/rsync -av outputs/$DOMAINS_RES/ $OutputDir/${DOMAINS_RES}km/ || {
+    echo "Failed to run /usr/bin/rsync -av outputs/$DOMAINS_RES/ $OutputDir/${DOMAINS_RES}km/"
     exit 1
   }
 done
diff --git a/PATH-SCRIPT-201607/met2camx/met2camx_run b/PATH-SCRIPT-201607/met2camx/met2camx_run
--- a/PATH-SCRIPT-201607/met2camx/met2camx_run
+++ b/PATH-SCRIPT-201607/met2camx/met2camx_run
@@ -8,7 +8,7 @@ MYNAME=`/bin/basename $0`
 ECHO="echo LOG:${MYNAME}:"
 
 if [ $# -eq 2 ]; then
-  YMDh=$1
+  INIT_TIME=$1
   MetData=$2
 else
   $ECHO "Usage: Init_time Met_data"
@@ -34,7 +34,6 @@ else
   $ECHO "Invalid Met_data name ${MetData}, must be mm5 or wrf"
   exit 1
 fi 
-
 if [ $DAY1FIXED -eq 1 ]; then
   MET=${DATA_MET_INPUT}.day1fixed
 else
@@ -44,28 +43,28 @@ OUTPUT=$DATA_M2CX_OUTPUT
 
 echo "MET=$MET OUTPUT=$OUTPUT"
 
-if [ ${#YMDh} -ne 10 ]; then
-  $ECHO "Invalid initial datetime $YMDh, must be in YYYYMMDDhh format"
+if [ ${#INIT_TIME} -ne 10 ]; then
+  $ECHO "Invalid initial datetime $INIT_TIME, must be in YYYYMMDDhh format"
   exit 1
 fi
 
-tt=`/bin/date -d "${YMDh:0:8} ${YMDh:8:2}:00:00" +%Y%m%d%H 2>/dev/null` || {
-  $ECHO "Invalid initial datetime $YMDh"
+tt=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00" +%Y%m%d%H 2>/dev/null` || {
+  $ECHO "Invalid initial datetime $INIT_TIME"
   exit 1
 }
 
-if [ "$tt" != "$YMDh" ]; then
-  $ECHO "Invalid initial datetime $YMDh"
+if [ "$tt" != "$INIT_TIME" ]; then
+  $ECHO "Invalid initial datetime $INIT_TIME"
   exit 1
 fi
 
-InitHr=${YMDh:8:2}
-if [ "$InitHr" != "00" -a "$InitHr" != "12" ]; then
-  $ECHO "Invalid initial datetime $YMDh, initial hour must be 00 or 12"
+INIT_H=${INIT_TIME:8:2}
+if [ "$INIT_H" != "00" -a "$INIT_H" != "12" ]; then
+  $ECHO "Invalid initial datetime $INIT_TIME, initial hour must be 00 or 12"
   exit 1
 fi
  
-MetData="$MET/${YMDh:0:4}/${YMDh:0:6}/${YMDh}"
+MetData="$MET/${INIT_TIME:0:4}/${INIT_TIME:0:6}/${INIT_TIME}"
 if [ ! -e $MetData ]; then
   $ECHO "No input Met data in $MetData"
   exit 1
@@ -81,51 +80,49 @@ cd $WorkDir || {
 }
 
 # CTM initial date
-YMD1=`/bin/date -d "${YMDh:0:8} $CTM_SKIP_N_DAYS days" +%Y%m%d`
+BEG_GDATE=`/bin/date -d "${INIT_TIME:0:8} $CTM_SKIP_N_DAYS days" +%Y%m%d`
 # CTM ending  date
-YMD2=`/bin/date -d "${YMD1:0:8} $CTM_SIM_N_DAYS days"  +%Y%m%d`
+END_TOM_GDATE=`/bin/date -d "${BEG_GDATE:0:8} $CTM_SIM_N_DAYS days"  +%Y%m%d`
 # CTM ending  date - 1
-YMD2_1d=`/bin/date -d "${YMD2:0:8} 1 day ago"  +%Y%m%d`
+END_GDATE=`/bin/date -d "${END_TOM_GDATE:0:8} 1 day ago"  +%Y%m%d`
 
-$ECHO YMD1=$YMD1 YMD2=$YMD2
+$ECHO BEG_GDATE=$BEG_GDATE END_TOM_GDATE=$END_TOM_GDATE
 
-YJ1=`./g2j ${YMD1:0:4} ${YMD1:4:2} ${YMD1:6:2}` || {
-  $ECHO $YJ1
+BEG_JDATE=`./g2j ${BEG_GDATE:0:4} ${BEG_GDATE:4:2} ${BEG_GDATE:6:2}` || {
+  $ECHO $BEG_JDATE
   exit 1
 }
-YJ2=`./g2j ${YMD2:0:4} ${YMD2:4:2} ${YMD2:6:2}` || {
-  $ECHO $YJ2
+END_TOM_JDATE=`./g2j ${END_TOM_GDATE:0:4} ${END_TOM_GDATE:4:2} ${END_TOM_GDATE:6:2}` || {
+  $ECHO $END_TOM_JDATE
   exit 1
 }
-YJ2_1d=`./g2j ${YMD2_1d:0:4} ${YMD2_1d:4:2} ${YMD2_1d:6:2}` || {
-  $ECHO $YJ2_1d
+END_JDATE=`./g2j ${END_GDATE:0:4} ${END_GDATE:4:2} ${END_GDATE:6:2}` || {
+  $ECHO $END_JDATE
   exit 1
 }
 
-$ECHO YJ1=$YJ1 YJ2=$YJ2 YJ2_1d=$YJ2_1d
+$ECHO BEG_JDATE=$BEG_JDATE END_TOM_JDATE=$END_TOM_JDATE END_JDATE=$END_JDATE
 
 /usr/bin/find . -type l -name "${Prefix}_d0*" -exec /bin/rm -f {} \;
 
-$ECHO $LinkProg $YJ1 $YJ2 $InitHr $MET
-$LinkProg $YJ1 $YJ2 $InitHr $MET || {
-  $ECHO "Failed to run $LinkProg $YJ1 $YJ2 $MET in $WorkDir"
+$ECHO $LinkProg $BEG_JDATE $END_TOM_JDATE $INIT_H $MET
+$LinkProg $BEG_JDATE $END_TOM_JDATE $INIT_H $MET || {
+  $ECHO "Failed to run $LinkProg $BEG_JDATE $END_TOM_JDATE $MET in $WorkDir"
   exit 1
 }
-
-Met2Camx=${Met2Camx}-${InitHr}
-$ECHO $Met2Camx $YJ1 $YJ2_1d
-$Met2Camx $YJ1 $YJ2_1d || {
-  $ECHO "Failed to run $Met2Camx $YJ1 $YJ2_1d"
+Met2Camx=${Met2Camx}-${INIT_H}
+$ECHO $Met2Camx $BEG_JDATE $END_JDATE
+$Met2Camx $BEG_JDATE $END_JDATE || {
+  $ECHO "Failed to run $Met2Camx $BEG_JDATE $END_JDATE"
   exit 1
 }
-
 cd $MYDIR || exit 1
-./check_output ${YMD1} ${YMD2} || {
-  $ECHO "Failed to run ./check_output ${YMD1} ${YMD2}"
+./check_output ${BEG_GDATE} ${END_TOM_GDATE} || {
+  $ECHO "Failed to run ./check_output ${BEG_GDATE} ${END_TOM_GDATE}"
   exit 1
 } 
 
-OUTPUTData=$OUTPUT/${YMDh:0:4}/${YMDh:0:6}/${YMDh}
+OUTPUTData=$OUTPUT/${INIT_TIME:0:4}/${INIT_TIME:0:6}/${INIT_TIME}
 if [ -d $OUTPUTData ]; then
   $ECHO "Output data directory $OUTPUTData already exists"
   if [ $CTM_CLEAN_OUTPUT -eq 1 ]; then
